"""Product catalog for Printalaram.

Each product carries a `layout` config describing where the customer's Name /
Family Name / Photo should be composited on that specific card's artwork
(positions vary per design). More designs will be appended here over time.
"""

CATEGORIES = [
    {"id": "sacred-tradition", "name": "Sacred Tradition", "description": "Spiritual & devotional designs", "cardIndexes": [1, 2, 3, 4, 5]},
    {"id": "wedding-royal", "name": "Wedding Royal", "description": "Premium wedding shagun designs", "cardIndexes": [6, 7, 8, 9, 10]},
]

PRODUCTS = [
    {
        "id": "card-1",
        "name": "Swaminarayan Lifafa",
        "slug": "swaminarayan-lifafa",
        "cardIndex": 1,
        "image": "/cards/card-1.jpeg",
        "gallery": ["/cards/card-1.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "sacred-tradition",
        "categoryName": "Sacred Tradition",
        "rating": 5.0,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-2",
        "name": "Pastel Peacock Lifafa",
        "slug": "pastel-peacock-lifafa",
        "cardIndex": 2,
        "image": "/cards/card-2.jpeg",
        "gallery": ["/cards/card-2.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "sacred-tradition",
        "categoryName": "Sacred Tradition",
        "rating": 4.5,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-3",
        "name": "Mahadev Theme Lifafa",
        "slug": "mahadev-theme-lifafa",
        "cardIndex": 3,
        "image": "/cards/card-3.jpeg",
        "gallery": ["/cards/card-3.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "sacred-tradition",
        "categoryName": "Sacred Tradition",
        "rating": 4.0,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-4",
        "name": "Royal Peacock Lifafa",
        "slug": "royal-peacock-lifafa",
        "cardIndex": 4,
        "image": "/cards/card-4.jpeg",
        "gallery": ["/cards/card-4.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "sacred-tradition",
        "categoryName": "Sacred Tradition",
        "rating": 5.0,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-5",
        "name": "Royal Wedding Shagun Lifafa",
        "slug": "royal-wedding-shagun-lifafa",
        "cardIndex": 5,
        "image": "/cards/card-5.jpeg",
        "gallery": ["/cards/card-5.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "sacred-tradition",
        "categoryName": "Sacred Tradition",
        "rating": 4.5,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-6",
        "name": "Elegant Green Floral Lifafa",
        "slug": "elegant-green-floral-lifafa",
        "cardIndex": 6,
        "image": "/cards/card-6.jpeg",
        "gallery": ["/cards/card-6.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "wedding-royal",
        "categoryName": "Wedding Royal",
        "rating": 4.0,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-7",
        "name": "Royal Peacock Garden Lifafa",
        "slug": "royal-peacock-garden-lifafa",
        "cardIndex": 7,
        "image": "/cards/card-7.jpeg",
        "gallery": ["/cards/card-7.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "wedding-royal",
        "categoryName": "Wedding Royal",
        "rating": 3.5,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-8",
        "name": "Pichwai Cow Lifafa",
        "slug": "pichwai-cow-lifafa",
        "cardIndex": 8,
        "image": "/cards/card-8.jpeg",
        "gallery": ["/cards/card-8.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "wedding-royal",
        "categoryName": "Wedding Royal",
        "rating": 5.0,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-9",
        "name": "Shreenathji Lifafa",
        "slug": "shreenathji-lifafa",
        "cardIndex": 9,
        "image": "/cards/card-9.jpeg",
        "gallery": ["/cards/card-9.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "wedding-royal",
        "categoryName": "Wedding Royal",
        "rating": 4.5,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
    {
        "id": "card-10",
        "name": "Pastel Peacock Lifafa",
        "slug": "pastel-peacock-lifafa",
        "cardIndex": 10,
        "image": "/cards/card-10.jpeg",
        "gallery": ["/cards/card-10.jpeg"],
        "price": 15,
        "originalPrice": 49,
        "discount": round(((49 - 15) / 49) * 100),
        "category": "wedding-royal",
        "categoryName": "Wedding Royal",
        "rating": 5.0,
        "reviewCount": 2,
        "bestSeller": False,
        "featured": False,
        "inStock": True,
        "description": "",
        "features": [],
        "photoUploadEnabled": True,
        "sizes": ["Standard (4.5\" x 8.5\")"],
        "layout": {
            "photo": {"top": "20%", "left": "10%", "width": "30%", "height": "30%"},
            "name": {"top": "60%", "color": "#ffffff"},
            "family": {"top": "70%", "color": "#e8c874"},
        },
    },
]
